site_name: NeuroGeriatricsMotionToolbox NGMT

theme:
  name: "mkdocs"
  language: en
  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_css:
  - 'style.css'

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ngmt]

theme:
  logo: ng_logo.png
  name: material
  palette:
    primary: light green
    accent: purple
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Examples: 
    - examples/index.md
    - Tutorial basics: examples/00_tutorial_basics.md
    - Events in dataclass: examples/04_tutorial_events_in_dataclass.md
    - Gait Sequence Detection: examples/01_tutorial_gait_sequence_detection.md
    - Initial Contact Detection: examples/02_tutorial_initial_contact_detection.md
    - Physical Activity Monitoring: examples/03_tutorial_physical_activity_monitoring.md
    - Sit to Stand and Stand to Sit Detection: examples/05_tutorial_sit_to_stand_stand_to_sit_detection.md
  - Modules: 
    - modules/index.md
    - Gait Sequence Detection: modules/gsd.md
    - Initial Contact Detection: modules/icd.md
    - Physical Activity Monitoring: modules/pam.md
    - Sit to Stand and Stand to Sit Detection: modules/ssd.md
  - Dataclasses: dataclass.md
  - Datasets: datasets.md
    - datasets/index.md
    - KeepControl: datasets/keepcontrol.md
    - Mobilise-D: datasets/mobilised.md
    - Fair-Park II: datasets/fairpark.md
  - Utilities: utils.md

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

