site_name: NeuroGeriatricsMotionToolbox NGMT

theme:
  name: "mkdocs"

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ngmt]

theme:
  logo: ng_logo.png
  name: material
  palette:
    primary: light green
    accent: purple


nav:
  - index.md
  - Datasets: datasets.md
  - Dataclasses: dataclasses.md
  - Modules: modules.md
  - Utilities: utils.md
  - Examples: examples/event_visualization.ipynb

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

