site_name: NeuroGeriatricsMotionToolbox NGMT

theme:
  name: "mkdocs"
  language: en
  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_css:
  - 'style.css'

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ngmt]

theme:
  logo: ng_logo.png
  name: material
  palette:
    primary: light green
    accent: purple
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Examples: examples.md
  - Modules: modules.md
  - Dataclasses: dataclasses.md
  - Datasets: datasets.md
  - Utilities: utils.md

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

